/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletIndexRouteImport } from './routes/wallet/index'
import { Route as SellIndexRouteImport } from './routes/sell/index'
import { Route as WalletCashInRouteImport } from './routes/wallet/cash-in'
import { Route as SellNewRouteImport } from './routes/sell/new'
import { Route as AuctionsIdRouteImport } from './routes/auctions/$id'
import { Route as AdminKycRouteImport } from './routes/admin/kyc'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountKycRouteImport } from './routes/account/kyc'
import { Route as SellIdEditRouteImport } from './routes/sell/$id.edit'
import { Route as ApiWebhooksPaymongoRouteImport } from './routes/api/webhooks/paymongo'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellIndexRoute = SellIndexRouteImport.update({
  id: '/sell/',
  path: '/sell/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletCashInRoute = WalletCashInRouteImport.update({
  id: '/wallet/cash-in',
  path: '/wallet/cash-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SellNewRoute = SellNewRouteImport.update({
  id: '/sell/new',
  path: '/sell/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIdRoute = AuctionsIdRouteImport.update({
  id: '/auctions/$id',
  path: '/auctions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/admin/kyc',
  path: '/admin/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountKycRoute = AccountKycRouteImport.update({
  id: '/account/kyc',
  path: '/account/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const SellIdEditRoute = SellIdEditRouteImport.update({
  id: '/sell/$id/edit',
  path: '/sell/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPaymongoRoute = ApiWebhooksPaymongoRouteImport.update({
  id: '/api/webhooks/paymongo',
  path: '/api/webhooks/paymongo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/kyc': typeof AccountKycRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/kyc': typeof AdminKycRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/sell/new': typeof SellNewRoute
  '/wallet/cash-in': typeof WalletCashInRoute
  '/sell/': typeof SellIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/api/webhooks/paymongo': typeof ApiWebhooksPaymongoRoute
  '/sell/$id/edit': typeof SellIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/kyc': typeof AccountKycRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/kyc': typeof AdminKycRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/sell/new': typeof SellNewRoute
  '/wallet/cash-in': typeof WalletCashInRoute
  '/sell': typeof SellIndexRoute
  '/wallet': typeof WalletIndexRoute
  '/api/webhooks/paymongo': typeof ApiWebhooksPaymongoRoute
  '/sell/$id/edit': typeof SellIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/kyc': typeof AccountKycRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/kyc': typeof AdminKycRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/sell/new': typeof SellNewRoute
  '/wallet/cash-in': typeof WalletCashInRoute
  '/sell/': typeof SellIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/api/webhooks/paymongo': typeof ApiWebhooksPaymongoRoute
  '/sell/$id/edit': typeof SellIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/account/kyc'
    | '/account/profile'
    | '/admin/kyc'
    | '/auctions/$id'
    | '/sell/new'
    | '/wallet/cash-in'
    | '/sell/'
    | '/wallet/'
    | '/api/webhooks/paymongo'
    | '/sell/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/account/kyc'
    | '/account/profile'
    | '/admin/kyc'
    | '/auctions/$id'
    | '/sell/new'
    | '/wallet/cash-in'
    | '/sell'
    | '/wallet'
    | '/api/webhooks/paymongo'
    | '/sell/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/account/kyc'
    | '/account/profile'
    | '/admin/kyc'
    | '/auctions/$id'
    | '/sell/new'
    | '/wallet/cash-in'
    | '/sell/'
    | '/wallet/'
    | '/api/webhooks/paymongo'
    | '/sell/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AccountKycRoute: typeof AccountKycRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AdminKycRoute: typeof AdminKycRoute
  AuctionsIdRoute: typeof AuctionsIdRoute
  SellNewRoute: typeof SellNewRoute
  WalletCashInRoute: typeof WalletCashInRoute
  SellIndexRoute: typeof SellIndexRoute
  WalletIndexRoute: typeof WalletIndexRoute
  ApiWebhooksPaymongoRoute: typeof ApiWebhooksPaymongoRoute
  SellIdEditRoute: typeof SellIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/wallet'
      fullPath: '/wallet/'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/': {
      id: '/sell/'
      path: '/sell'
      fullPath: '/sell/'
      preLoaderRoute: typeof SellIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/cash-in': {
      id: '/wallet/cash-in'
      path: '/wallet/cash-in'
      fullPath: '/wallet/cash-in'
      preLoaderRoute: typeof WalletCashInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/new': {
      id: '/sell/new'
      path: '/sell/new'
      fullPath: '/sell/new'
      preLoaderRoute: typeof SellNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$id': {
      id: '/auctions/$id'
      path: '/auctions/$id'
      fullPath: '/auctions/$id'
      preLoaderRoute: typeof AuctionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/admin/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/kyc': {
      id: '/account/kyc'
      path: '/account/kyc'
      fullPath: '/account/kyc'
      preLoaderRoute: typeof AccountKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/$id/edit': {
      id: '/sell/$id/edit'
      path: '/sell/$id/edit'
      fullPath: '/sell/$id/edit'
      preLoaderRoute: typeof SellIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/paymongo': {
      id: '/api/webhooks/paymongo'
      path: '/api/webhooks/paymongo'
      fullPath: '/api/webhooks/paymongo'
      preLoaderRoute: typeof ApiWebhooksPaymongoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AccountKycRoute: AccountKycRoute,
  AccountProfileRoute: AccountProfileRoute,
  AdminKycRoute: AdminKycRoute,
  AuctionsIdRoute: AuctionsIdRoute,
  SellNewRoute: SellNewRoute,
  WalletCashInRoute: WalletCashInRoute,
  SellIndexRoute: SellIndexRoute,
  WalletIndexRoute: WalletIndexRoute,
  ApiWebhooksPaymongoRoute: ApiWebhooksPaymongoRoute,
  SellIdEditRoute: SellIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
