/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletIndexRouteImport } from './routes/wallet/index'
import { Route as SellIndexRouteImport } from './routes/sell/index'
import { Route as AuctionsIndexRouteImport } from './routes/auctions/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as WalletCashInRouteImport } from './routes/wallet/cash-in'
import { Route as SellNewRouteImport } from './routes/sell/new'
import { Route as AuctionsIdRouteImport } from './routes/auctions/$id'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminKycRouteImport } from './routes/admin/kyc'
import { Route as AdminBidsRouteImport } from './routes/admin/bids'
import { Route as AdminAuctionsRouteImport } from './routes/admin/auctions'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountKycRouteImport } from './routes/account/kyc'
import { Route as SellIdEditRouteImport } from './routes/sell/$id.edit'
import { Route as ApiWebhooksPaymongoRouteImport } from './routes/api/webhooks/paymongo'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellIndexRoute = SellIndexRouteImport.update({
  id: '/sell/',
  path: '/sell/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIndexRoute = AuctionsIndexRouteImport.update({
  id: '/auctions/',
  path: '/auctions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletCashInRoute = WalletCashInRouteImport.update({
  id: '/wallet/cash-in',
  path: '/wallet/cash-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SellNewRoute = SellNewRouteImport.update({
  id: '/sell/new',
  path: '/sell/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsIdRoute = AuctionsIdRouteImport.update({
  id: '/auctions/$id',
  path: '/auctions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBidsRoute = AdminBidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuctionsRoute = AdminAuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountKycRoute = AccountKycRouteImport.update({
  id: '/account/kyc',
  path: '/account/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const SellIdEditRoute = SellIdEditRouteImport.update({
  id: '/sell/$id/edit',
  path: '/sell/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPaymongoRoute = ApiWebhooksPaymongoRouteImport.update({
  id: '/api/webhooks/paymongo',
  path: '/api/webhooks/paymongo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/kyc': typeof AccountKycRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/bids': typeof AdminBidsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/users': typeof AdminUsersRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/sell/new': typeof SellNewRoute
  '/wallet/cash-in': typeof WalletCashInRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/sell/': typeof SellIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/api/webhooks/paymongo': typeof ApiWebhooksPaymongoRoute
  '/sell/$id/edit': typeof SellIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/kyc': typeof AccountKycRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/bids': typeof AdminBidsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/users': typeof AdminUsersRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/sell/new': typeof SellNewRoute
  '/wallet/cash-in': typeof WalletCashInRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/auctions': typeof AuctionsIndexRoute
  '/sell': typeof SellIndexRoute
  '/wallet': typeof WalletIndexRoute
  '/api/webhooks/paymongo': typeof ApiWebhooksPaymongoRoute
  '/sell/$id/edit': typeof SellIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/kyc': typeof AccountKycRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/auctions': typeof AdminAuctionsRoute
  '/admin/bids': typeof AdminBidsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/users': typeof AdminUsersRoute
  '/auctions/$id': typeof AuctionsIdRoute
  '/sell/new': typeof SellNewRoute
  '/wallet/cash-in': typeof WalletCashInRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auctions/': typeof AuctionsIndexRoute
  '/sell/': typeof SellIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/api/webhooks/paymongo': typeof ApiWebhooksPaymongoRoute
  '/sell/$id/edit': typeof SellIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/account/kyc'
    | '/account/profile'
    | '/admin/auctions'
    | '/admin/bids'
    | '/admin/kyc'
    | '/admin/users'
    | '/auctions/$id'
    | '/sell/new'
    | '/wallet/cash-in'
    | '/account/'
    | '/admin/'
    | '/auctions/'
    | '/sell/'
    | '/wallet/'
    | '/api/webhooks/paymongo'
    | '/sell/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/account/kyc'
    | '/account/profile'
    | '/admin/auctions'
    | '/admin/bids'
    | '/admin/kyc'
    | '/admin/users'
    | '/auctions/$id'
    | '/sell/new'
    | '/wallet/cash-in'
    | '/account'
    | '/admin'
    | '/auctions'
    | '/sell'
    | '/wallet'
    | '/api/webhooks/paymongo'
    | '/sell/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/account/kyc'
    | '/account/profile'
    | '/admin/auctions'
    | '/admin/bids'
    | '/admin/kyc'
    | '/admin/users'
    | '/auctions/$id'
    | '/sell/new'
    | '/wallet/cash-in'
    | '/account/'
    | '/admin/'
    | '/auctions/'
    | '/sell/'
    | '/wallet/'
    | '/api/webhooks/paymongo'
    | '/sell/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AccountKycRoute: typeof AccountKycRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AuctionsIdRoute: typeof AuctionsIdRoute
  SellNewRoute: typeof SellNewRoute
  WalletCashInRoute: typeof WalletCashInRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AuctionsIndexRoute: typeof AuctionsIndexRoute
  SellIndexRoute: typeof SellIndexRoute
  WalletIndexRoute: typeof WalletIndexRoute
  ApiWebhooksPaymongoRoute: typeof ApiWebhooksPaymongoRoute
  SellIdEditRoute: typeof SellIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/wallet'
      fullPath: '/wallet/'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/': {
      id: '/sell/'
      path: '/sell'
      fullPath: '/sell/'
      preLoaderRoute: typeof SellIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/': {
      id: '/auctions/'
      path: '/auctions'
      fullPath: '/auctions/'
      preLoaderRoute: typeof AuctionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/cash-in': {
      id: '/wallet/cash-in'
      path: '/wallet/cash-in'
      fullPath: '/wallet/cash-in'
      preLoaderRoute: typeof WalletCashInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/new': {
      id: '/sell/new'
      path: '/sell/new'
      fullPath: '/sell/new'
      preLoaderRoute: typeof SellNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$id': {
      id: '/auctions/$id'
      path: '/auctions/$id'
      fullPath: '/auctions/$id'
      preLoaderRoute: typeof AuctionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bids': {
      id: '/admin/bids'
      path: '/bids'
      fullPath: '/admin/bids'
      preLoaderRoute: typeof AdminBidsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/auctions': {
      id: '/admin/auctions'
      path: '/auctions'
      fullPath: '/admin/auctions'
      preLoaderRoute: typeof AdminAuctionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/kyc': {
      id: '/account/kyc'
      path: '/account/kyc'
      fullPath: '/account/kyc'
      preLoaderRoute: typeof AccountKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/$id/edit': {
      id: '/sell/$id/edit'
      path: '/sell/$id/edit'
      fullPath: '/sell/$id/edit'
      preLoaderRoute: typeof SellIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/paymongo': {
      id: '/api/webhooks/paymongo'
      path: '/api/webhooks/paymongo'
      fullPath: '/api/webhooks/paymongo'
      preLoaderRoute: typeof ApiWebhooksPaymongoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuctionsRoute: typeof AdminAuctionsRoute
  AdminBidsRoute: typeof AdminBidsRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuctionsRoute: AdminAuctionsRoute,
  AdminBidsRoute: AdminBidsRoute,
  AdminKycRoute: AdminKycRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AccountKycRoute: AccountKycRoute,
  AccountProfileRoute: AccountProfileRoute,
  AuctionsIdRoute: AuctionsIdRoute,
  SellNewRoute: SellNewRoute,
  WalletCashInRoute: WalletCashInRoute,
  AccountIndexRoute: AccountIndexRoute,
  AuctionsIndexRoute: AuctionsIndexRoute,
  SellIndexRoute: SellIndexRoute,
  WalletIndexRoute: WalletIndexRoute,
  ApiWebhooksPaymongoRoute: ApiWebhooksPaymongoRoute,
  SellIdEditRoute: SellIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
